# (HTTP and SOCKS5 in one port)
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090

proxies:
  - {"name":"V4-中转9999|广港-新加坡|x2.5|V2ray","type":"vmess","server":"linode-zy.ddns-only.xyz","port":51196,"uuid":"d1eecbbb-c536-3d5e-afdb-28f7a427c042","alterId":0,"cipher":"auto","udp":true,"network":"ws","ws-path":"/v2ray","ws-headers":{"Host":"linode-zy.ddns-only.xyz"}}


proxy-providers:
  j01.best:
    type: http
    path: ./profiles/j01.best.yaml
    url: https://suo.yt/hdShNIS
    interval: 43200
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 1800
# 订阅链接转换：
## 地址：https://bianyuan.xyz/
## Exclude：(\d\d\.|I\.|I\+|过期)
## 原始v2ray链接：https://j03.space/link/jvypUv7tZqyFBtC5?clash=2


proxy-groups: 
  - name: PROXY
    type: select
    proxies:
      - V4-中转9999|广港-新加坡|x2.5|V2ray
      - url-test-auto
      - fallback-auto
    use:
      - j01.best

# interval 单位为s
# 自动选择最低延迟服务器
  - name: url-test-auto
    type: url-test
    use:
      - j01.best
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800
    tolerance: 100

# 按照用户书写的服务器顺序，在确保服务器可用的情况下，自动选择服务器
  - name: fallback-auto
    type: fallback
    use:
      - j01.best
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800




rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 43200

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 43200

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 43200

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 43200


rules:
# Spotiy
 - DOMAIN-SUFFIX,audio-ak-spotify-com.akamaized.net, DIRECT
 - DOMAIN-SUFFIX,audio-ake.spotify.com.edgesuite.net, DIRECT
 - DOMAIN-SUFFIX,scdn.co, DIRECT
 - DOMAIN,spclient.wg.spotify.com, REJECT

# My Rules
 - RULE-SET,reject,REJECT
 - DOMAIN-SUFFIX,access-sngapm.qcloud.com , REJECT

 - RULE-SET,lancidr,DIRECT
 - RULE-SET,private,DIRECT
 - RULE-SET,direct,DIRECT
 - DOMAIN-SUFFIX,store.steampowered.com,DIRECT
 - IP-CIDR,172.18.254.245/24, DIRECT
 - GEOIP,CN,DIRECT

 - MATCH,PROXY
