# (HTTP and SOCKS5 in one port)
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090


mixin: # object
  hosts:
    'phicomm.me': 192.168.2.1
  dns:
    enable: true
    ipv6: false
    # listen: 0.0.0.0:53
    enhanced-mode: redir-host
    use-hosts: true
    fake-ip-filter:
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - 'www.msftconnecttest.com'
      - '+.qq.com'
      - '+.music.163.com'
      - '+.music.162.com'
    default-nameserver:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 8.8.8.8
      - 114.114.114.114
      - 1.1.1.1
    fallback:
      - 'https://1.1.1.1/dns-query'
      - 'https://162.159.36.1/dns-query'
      - 'https://162.14.13.12/dns-query'
      - 'tls://dns.rubyfish.cn:853'
      - 'tls://1.0.0.1:853'
      - 'tls://dns.google:853'
    fallback-filter:
      geoip: true
      ipcidr:
        - 0.0.0.0/32
        - 127.0.0.0/8
        - 240.0.0.0/4

proxies:
  - {"name":"V4-中转9999|广港-新加坡|x2.5|V2ray","type":"vmess","server":"linode-zy.ddns-only.xyz","port":51196,"uuid":"d1eecbbb-c536-3d5e-afdb-28f7a427c042","alterId":0,"cipher":"auto","udp":true,"network":"ws","ws-path":"/v2ray","ws-headers":{"Host":"linode-zy.ddns-only.xyz"}}


proxy-providers:
  j01.best:
    type: http
    path: ./profiles/j01.best.yaml
    url: https://suo.yt/hdShNIS
    interval: 43200
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 1800
# 订阅链接转换：
## 地址：https://bianyuan.xyz/
## Exclude：(\d\d\.|I\.|I\+|过期)
## 原始v2ray链接：https://j03.space/link/jvypUv7tZqyFBtC5?clash=2


proxy-groups: 
  - name: PROXY
    type: select
    proxies:
      - V4-中转9999|广港-新加坡|x2.5|V2ray
      - url-test-auto
      - fallback-auto
    use:
      - j01.best

# interval 单位为s
# 自动选择最低延迟服务器
  - name: url-test-auto
    type: url-test
    use:
      - j01.best
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800
    tolerance: 100

# 按照用户书写的服务器顺序，在确保服务器可用的情况下，自动选择服务器
  - name: fallback-auto
    type: fallback
    use:
      - j01.best
    url: 'http://www.gstatic.com/generate_204'
    interval: 1800




rule-providers:

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./RuleSet/lancidr.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./RuleSet/private.yaml
    interval: 86400
  
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./RuleSet/reject.yaml
    interval: 86400
    
  reject_anti-AD:
    type: http
    behavior: domain
    url: "https://anti-ad.net/clash.yaml"
    path: ./RuleSet/reject_anti-AD.yaml
    interval: 86400
        
  Advertising:
    type: http
    behavior: classical
    path: ./RuleSet/Advertising.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
    interval: 86400

  Advertising_Classical:
    type: http
    behavior: classical
    path: ./RuleSet/Advertising_Classical.yaml
    url:  https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400

  Advertising_Domain:
    type: http
    behavior: domain
    path: ./RuleSet/Advertising_Domain.yaml
    url:  https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml
    interval: 86400
 
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./RuleSet/direct.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400


rules:
# 科大
 - IP-CIDR,172.18.254.245/24, DIRECT
 
 - DOMAIN-SUFFIX,access-sngapm.qcloud.com,REJECT
 - DOMAIN-SUFFIX,gleam.io,DIRECT
 - DOMAIN-SUFFIX,pinyuncloud.com,DIRECT
 - IP-CIDR,185.199.111.133/24, PROXY
 
# Spotiy
 - DOMAIN-SUFFIX,audio-ak-spotify-com.akamaized.net,DIRECT
 - DOMAIN-SUFFIX,audio-ake.spotify.com.edgesuite.net,DIRECT
 - DOMAIN-SUFFIX,scdn.co,DIRECT
 - DOMAIN,spclient.wg.spotify.com,REJECT

# RULE-SET 
 - RULE-SET,lancidr,DIRECT
 - RULE-SET,private,DIRECT
 
# - RULE-SET,reject,REJECT
# - RULE-SET,reject_anti-AD,REJECT
 - RULE-SET,Unbreak,DIRECT
 - RULE-SET,Advertising,DIRECT
 - RULE-SET,Advertising_Classical,DIRECT
 - RULE-SET,Advertising_Domain,DIRECT

 - RULE-SET,direct,DIRECT
 - RULE-SET,China,DIRECT
 - RULE-SET,ChinaIP,DIRECT

 - MATCH,PROXY
