name: Daily Merge Moyu_clash.list

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 00:00 自动执行
  workflow_dispatch:     # 支持手动触发

jobs:
  merge-yamls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download remote YAML files
        run: |
          # 下载外部 yaml（失败不停止，-sfL）
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/36kr/36kr.yaml -o 36kr.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml -o BiliBili.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouBan/DouBan.yaml -o DouBan.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml -o DouYin.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hupu/Hupu.yaml -o Hupu.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuYa/HuYa.yaml -o HuYa.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/JingDong/JingDong.yaml -o JingDong.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NGA/NGA.yaml -o NGA.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SMZDM/SMZDM.yaml -o SMZDM.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TianYaForum/TianYaForum.yaml -o TianYaForum.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.yaml -o Weibo.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Zhihu/Zhihu.yaml -o Zhihu.yaml

      - name: Merge files with custom header (with last-update line)
        run: |
          # 这里我们选择使用 Asia/Shanghai 时区（北京时间）。如果你想用 UTC，请把 TZ=Asia/Shanghai 改为 date -u
          # 1) 生成 header（使用 > 覆盖旧文件）
          echo "# Moyu_clash.list" > Moyu_clash.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash" >> Moyu_clash.list
          # 写入“最后更新时间”这一行（每次运行会被更新为最新时间）
          echo "# 最后更新时间: $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S %z %Z')" >> Moyu_clash.list

          # 2) 写入一些固定的规则（追加）
          echo "" >> Moyu_clash.list
          echo "DOMAIN,keylol.com" >> Moyu_clash.list
          echo "DOMAIN,sspai.com" >> Moyu_clash.list
          echo "DOMAIN,www.163.com" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,chongbuluo.com" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,douyin.com" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,huxiu.com" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,jandan.net" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,kdslife.com" >> Moyu_clash.list
          echo "DOMAIN-SUFFIX,tophub.today" >> Moyu_clash.list

          echo "" >> Moyu_clash.list
          # 3) 将下载的各个 yaml 内容追加到最终文件
          cat 36kr.yaml BiliBili.yaml DouBan.yaml DouYin.yaml Hupu.yaml HuYa.yaml JingDong.yaml NGA.yaml SMZDM.yaml TianYaForum.yaml Weibo.yaml Zhihu.yaml >> Moyu_clash.list

      - name: Commit and push Moyu_clash.list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 配置提交信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Moyu_clash.list
          # 只有在有变更时才提交（时间戳或内容变化都会触发提交）
          if ! git diff --cached --quiet; then
            git commit -m "Daily merge YAMLs: $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S %z')"
            git push origin HEAD:main
          else
            echo "No changes, skipping commit."
          fi
