name: Daily Merge moyu.list

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 00:00 自动执行
  workflow_dispatch:     # 支持手动触发

jobs:
  merge-yamls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download remote YAML files
        run: |
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml -o BiliBili.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouBan/DouBan.yaml -o DouBan.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml -o DouYin.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hupu/Hupu.yaml -o Hupu.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/JingDong/JingDong.yaml -o JingDong.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NGA/NGA.yaml -o NGA.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SMZDM/SMZDM.yaml -o SMZDM.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TianYaForum/TianYaForum.yaml -o TianYaForum.yaml
          curl -sfL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.yaml -o Weibo.yaml

      - name: Merge files with custom header
        run: |
          echo "# Merged on $(date -u)" > moyu.list
          echo "DOMAIN-SUFFIX,tophub.today" >> moyu.list
          echo "DOMAIN-SUFFIX,jandan.net" >> moyu.list
          echo "" >> moyu.list
          cat BiliBili.yaml DouBan.yaml DouYin.yaml Hupu.yaml JingDong.yaml NGA.yaml SMZDM.yaml TianYaForum.yaml Weibo.yaml >> moyu.list

      - name: Commit and push moyu.list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add moyu.list
          if ! git diff --cached --quiet; then
            git commit -m "Daily merge YAMLs: $(date -u +'%Y-%m-%d')"
            git push origin HEAD:main
          else
            echo "No changes, skipping commit."
          fi
